name: dash-ops
image:
  name: dashops/dash-ops
  tag: 0.0.1

container:
  limits:
    memory: 600Mi
  requests:
    memory: 600Mi  
  httpPort: 8080
  probes:
    readinessDelay: 60
    livenessDelay: 180
    path: /api/health
  env:
    DASH_CONFIG: /dash-ops.yaml
  secrets: {}

ingress:
  enabled: false
  externalDNSTarget: traefik.local.
  hosts: []
