name: dash-ops
image:
  name: dashops/dash-ops
  tag: latest

container:
  limits:
    memory: 600Mi
  requests:
    memory: 600Mi  
  httpPort: 8080
  probes:
    readinessDelay: 60
    livenessDelay: 180
    path: /api/health
  env: {}
  secrets: {}

ingress:
  enabled: false
  externalDNSTarget: traefik.local.
  hosts: []

configMap: |
  # Use the example found in the project readme: https://github.com/dash-ops/dash-ops#running-on-a-kubernetes-cluster
