apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - list
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
subjects:
- kind: ServiceAccount
  name: {{.Values.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.name}}
