apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{.Values.container.httpPort}}
  selector:
    app: {{.Values.name}}
  sessionAffinity: None
  type: NodePort
